S3_TEST_BUCKET_NAME = 'ye-olde-bucket'
INGEST_AUDIT_TABLE_NAME = 'public.v1_ingest_audit'


TEST_REDSHIFT_DATABASE = 'aws_etl_tools_redshift_test'
TEST_POSTGRES_DATABASE = 'aws_etl_tools_postgres_test'
DEFAULT_POSTGRES_DATABASE_NAME = 'postgres'
EXISTING_LOCAL_DATABASE_USER = 'postgres'
EXISTING_LOCAL_DATABASE_PASSWORD = ''
TEST_DATABASE_PORT = 5432
TEST_DATABASE_HOST = 'localhost'

POSTGRES_TEST_CREDENTIALS = {
    'database_name': TEST_POSTGRES_DATABASE,
    'username': EXISTING_LOCAL_DATABASE_USER,
    'password': EXISTING_LOCAL_DATABASE_PASSWORD,
    'port': TEST_DATABASE_PORT,
    'host': TEST_DATABASE_HOST
}

REDSHIFT_TEST_CREDENTIALS = {
    'database_name': TEST_REDSHIFT_DATABASE,
    'username': EXISTING_LOCAL_DATABASE_USER,
    'password': EXISTING_LOCAL_DATABASE_PASSWORD,
    'port': TEST_DATABASE_PORT,
    'host': TEST_DATABASE_HOST
}

EXISTING_POSTGRES_CREDENTIALS = {
    'database_name': DEFAULT_POSTGRES_DATABASE_NAME,
    'username': EXISTING_LOCAL_DATABASE_USER,
    'password': EXISTING_LOCAL_DATABASE_PASSWORD,
    'port': TEST_DATABASE_PORT,
    'host': TEST_DATABASE_HOST
}

